// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nutbxgfkvtutuvrcjvgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51dGJ4Z2ZrdnR1dHV2cmNqdmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDA4MjgsImV4cCI6MjA2NDg3NjgyOH0.VluBbs5Pu9hoson4D-05kBQc9AC7uiNrXb3GJZA19Kg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);